service: graphdb-indexer
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  role: IamRoleGraphLambdaExecution
  stage: ${opt:stage, 'dev'}
  deploymentBucket: graphdb-driver-deployment-bucket-${opt:stage}
  vpc:
    securityGroupIds:
      - ${cf:${self:provider.stage}.servicesSecurityGroupId}
    subnetIds: !Split [',', '${cf:${self:provider.stage}.subnetIds}']
  environment:
    CMR_ROOT: ${self:custom.variables.CMR_ROOT}
    ENVIRONMENT: ${self:custom.variables.ENVIRONMENT}
    GREMLIN_URL: ${self:custom.variables.GREMLIN_URL}
    PAGE_SIZE: ${self:custom.variables.PAGE_SIZE}
plugins:
  - serverless-offline
  - serverless-pseudo-parameters
  - serverless-webpack
functions:
  bootstrapGremlinServer:
    timeout: 900
    handler: serverless/src/bootstrapGremlinServer/handler.default
  indexCmrCollection:
    timeout: 20
    handler: serverless/src/indexCmrCollection/handler.default
    events:
      - sqs:
          batchSize: 10
          arn: arn:aws:sqs:us-east-1:#{AWS::AccountId}:gsfc-eosdis-cmr-${self:provider.stage}-graphdb_queue
resources:
  Resources:
    IamRoleGraphLambdaExecution:
      Type: AWS::IAM::Role
      Properties:
        RoleName: cmrGraphRole-${self:provider.stage}
        PermissionsBoundary: arn:aws:iam::#{AWS::AccountId}:policy/NGAPShRoleBoundary
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: 'Allow'
              Principal:
                Service:
                  - 'lambda.amazonaws.com'
              Action:
                - 'sts:AssumeRole'
    cmrGraphPolicy:
      Type: AWS::IAM::Policy
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Action:
                - 'sqs:*'
              Effect: 'Allow'
              Resource: '*'
        PolicyName: cmrGraphPolicy-${self:provider.stage}
        Roles:
          - Ref: IamRoleGraphLambdaExecution
    cmrParamStorePolicy:
      Type: AWS::IAM::Policy
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Action:
                - 'ssm:GetParameter*'
                - 'secretsmanager:GetSecretValue'
              Effect: 'Allow'
              Resource:
                - 'arn:aws:ssm:*:*:parameter/${opt:stage}/graph-db/*'
        PolicyName: cmrParamStorePolicy-${opt:stage}
        Roles:
          - Ref: IamRoleGraphLambdaExecution
custom:
  variables:
    # Default values for environment variables
    CMR_ROOT: ${env:CMR_ROOT, 'https://cmr.sit.earthdata.nasa.gov'}
    ENVIRONMENT: ${self:provider.stage}
    GREMLIN_URL: ${env:GREMLIN_URL, 'wss://${cf:neptune-${opt:stage}.DBClusterEndpoint}:8182/gremlin'}
    PAGE_SIZE: ${env:PAGE_SIZE, '1000'}
